### ISSUE TITLE
Bot fails to get validated ledgers after updating to a new validator list

### ISSUE THREAD

**Issue by intelliot** [xpring-eng/validation-count-reporter#37]
A database that puts the bot into this bad state has been shared with @elmurci

**Comment by elmurci** [comment]
@intelliot the database you shared had the manifest table empty.
Not sure if that was caused by the trimming down of the DB you did.

The problem I have seen in the [collector](https://github.com/xpring-eng/validation-count-reporter/blob/a5b1ae45284ea6e6b40bdb6887608bea65f62892/src/collector.ts#L298) is that it was not loading new manifests as the `validator.manifestSequence` was equal to the retrieved `data.manifestSequence`:

```
if (
   validator.signing_key === undefined ||
   validator.manifestSequence < data.manifestSequence
) {
```
